### ISSUE TITLE
socru_species error (missing required positional argument: verbose)

### ISSUE THREAD

**Issue by Buuntu** [quadram-institute-bioscience/socru#12]
Getting this error when running socru_species:
```
Schemas().print_all()
TypeError: __init__() missing 1 required positional argument: 'verbose'
```

I installed socru using conda, and `socru` by itself seems to work fine (or print out the help message at least).  I checked that I have python 3.7 installed.

**Comment by andrewjpage** [comment]
Thank you for letting me know about this bug. I have fixed the software. It will take a little while for the changes to become available in conda.
