### ISSUE TITLE
Conda install not working

### ISSUE THREAD

**Issue by GeorgiaBreckell** [quadram-institute-bioscience/socru#16]
Have been using Socru previously but had to reinstall and when using the conda installation I got the following error: 

```(python3.6) georgia@gru:~$ socru
Traceback (most recent call last):
  File "/home/georgia/miniconda3/envs/python3.6/bin/socru", line 10, in <module>
    from socru.Socru import Socru
ModuleNotFoundError: No module named 'socru' 
```

The pip installation worked fine so I'm happily using this but just wanted to alert to the fact that the Conda installation had issues. 

For reference the conda install was into a clean environment on a linux machine.

**Comment by emmadoughty** [comment]
FYI, installation with conda still isn't working, though the error message has changed to:
```
Traceback (most recent call last):
  File "/usr/local/software/conda/envs/Socru/bin/socru", line 10, in <module>
    from socru.Socru import Socru
  File "/usr/local/software/conda/envs/Socru/lib/python3.8/site-packages/socru/Socru.py", line 13, in <module>
    from socru.FragmentFiles import FragmentFiles
  File "/usr/local/software/conda/envs/Socru/lib/python3.8/site-packages/socru/FragmentFiles.py", line 4, in <module>
    from Bio.Alphabet import generic_dna
  File "/usr/local/software/conda/envs/Socru/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
```
This was also into a new conda env

**Comment by thanhleviet** [comment]
> FYI, installation with conda still isn't working, though the error message has changed to:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/software/conda/envs/Socru/bin/socru", line 10, in <module>
>     from socru.Socru import Socru
>   File "/usr/local/software/conda/envs/Socru/lib/python3.8/site-packages/socru/Socru.py", line 13, in <module>
>     from socru.FragmentFiles import FragmentFiles
>   File "/usr/local/software/conda/envs/Socru/lib/python3.8/site-packages/socru/FragmentFiles.py", line 4, in <module>
>     from Bio.Alphabet import generic_dna
>   File "/usr/local/software/conda/envs/Socru/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
>     raise ImportError(
> ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
> ```
> 
> This was also into a new conda env

Hi @emmadoughty , this was due to a change in biopython 1.78 that breaks socru's code.
A quick fix at your end is:
If your conda env has python version ≤ 3.8, you just need to reinstall biopython < 1.78, i.e

```
conda install -c conda-forge -c bioconda "biopython<1.78"
```

otherwise, run the following commands:

```
conda create -n socru python=3.8
conda activate socru
conda install -c conda-forge -c bioconda socru biopython=1.77
```

I'll fix the conda recipe but it will take a bit of time to have socru updated on bioconda channel.

**Comment by thanhleviet** [comment]
A new build is now available on bioconda channel, the issue should be fixed.

**Comment by emmadoughty** [comment]
Thanks, @thanhleviet. That quick fix worked nicely!
